query queryUsersAndTeams {
  getUsers {
    id
    username
    tags
    profile {
      addresses {
        street
        city
        zipCode
      }
    }
  }
  getTeams {
    id
    location
  }
}
